E2LabPower/Areas/Admin/Controllers/SummryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using E2LabPower.Mangment;
using E2LabPower.Data;

namespace E2LabPower.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SummryController : Controller
    {
        private DataContext _context;

        public SummryController(DataContext context)
        {
            _context=context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetSummry()
        {
            return View();
        }
        [HttpPost]
        public IActionResult DetaildData(DateTime TimeDate, DateTime EndDate)
        {
            if(ModelState.IsValid)
            {
                var data = new SummryMangments(_context).GetAVGData(TimeDate, EndDate);
                ViewData["sd"]=TimeDate;
                ViewData["ed"]=EndDate;
                return View(data);
            }
            else
            {
                return View("GetSummry");
            }
        }

    }
}

E2LabPower/Areas/Admin/Views/Summry/DetaildData.cshtml
@model IEnumerable<E2LabPower.Domain.SummryDataModel.CircuitsWithFullDataSummry>

@{
    ViewData["Title"] = "DetaildData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Summary of Data</h2>
<br />

<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">

        <button type="button" class="btn btn-info">StartDate</button>
    </div>

    <div class="btn-group" role="group">
        <button type="button" class="btn btn-info">EndDate</button>
    </div>
</div>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@ViewData["sd"]</button>
    </div>

    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@ViewData["ed"] </button>
    </div>
</div>
<br />

<table class=" table table-bordered">
    <thead>
        <tr class="success">

                <th>
                    @Html.DisplayNameFor(model => model.CircuitName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LineName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VoltAVG)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AmpAVG)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PFAVG)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhaseAVG)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VoltVar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AmpVar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PFVAr)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhaseVar)
                </th>

           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td class="danger">
                @Html.DisplayFor(modelItem => item.CircuitName)
            </td>
            <td class="danger">
                @Html.DisplayFor(modelItem => item.LineName)
            </td>
            <td class="warning">
                @Html.DisplayFor(modelItem => item.VoltAVG)
            </td>
            <td class="warning">
                @Html.DisplayFor(modelItem => item.AmpAVG)
            </td>
            <td class="warning">
                @Html.DisplayFor(modelItem => item.PFAVG)
            </td>
            <td class="warning">
                @Html.DisplayFor(modelItem => item.PhaseAVG)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.VoltVar)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.AmpVar)
            </td>
            <td class="info">
                @Html.DisplayFor(modelItem => item.PFVAr)
            </td>
            <td class="info"    >
                @Html.DisplayFor(modelItem => item.PhaseVar)
            </td>


        </tr>
}
    </tbody>
</table>

E2LabPower/Areas/Admin/Views/Summry/GetSummry.cshtml
@model E2LabPower.Domain.SummryDataModel.CircuitsWithFullDataSummry
@{
    ViewData["Title"]="GetSummry";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

<h2>Summary of Data</h2>


@using(Html.BeginForm("DetaildData", "Summry"))
{<div class="text-danger" asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            @Html.LabelFor(m => m.StartDate)
            <input name="TimeDate" class="form-control" id="TimeDate" type="datetime-local"  data-val-required="Start Date is Required." data-val="true">
            @Html.ValidationMessageFor(m => m.StartDate)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.EndDate)
            <input name="EndDate" class="form-control" id="EndDate" type="datetime-local" data-val-required="End Date is Requied" data-val="true">
            @Html.ValidationMessageFor(m => m.EndDate)
        </div>


        <button type="submit"  class="btn btn-s btn-danger pull-right">
           Calculate
        </button>
}