E2LabPower/Areas/Admin/Controllers/EnargyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using E2LabPower.Domain.Enargy;
using E2LabPower.Mangment.ReportsMangments;
using E2LabPower.Data;
using E2LabPower.Domain;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;

namespace E2LabPower.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EnargyController : Controller
    {
        private readonly DataContext _Context;
        private IMemoryCache memoryCache;
        private IConfiguration configuration;

        public EnargyController(DataContext data)
        {
            _Context=data;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CalCulateEnargy()
        {
            var ViewModel = new EnargyDataModel()
            {
                Sources=new VarianceReportMangment(_Context).GetAllSources(),
            };

            return View(ViewModel);

        }
        [HttpGet]
        public JsonResult GetLines(int SourceID)
        {

            var Data = new LineService(_Context, memoryCache, configuration).GetLinesBySourceID(SourceID).ToList();
            return Json(new SelectList(Data, "LineID", "LineName"));
        }
        [HttpPost]
        public IActionResult GetEnargy(EnargyDataModel obj)
        {
         
            if(ModelState.IsValid)
            {
                obj.MID=5;
                var z = new EnargyReportMangement(_Context).CalculateEnergyFromAVG(obj);
                if(z.EnargyValue!=0)
                {
                    return View(z);
                }
                else
                {
                    ModelState.AddModelError("", "There Is No Energy In this Circuit");
                    return View(z);
                }
            }
            else
            {
                obj.Sources=new VarianceReportMangment(_Context).GetAllSources();
                return View("CalCulateEnargy", obj);
            }
        }
        public IActionResult CalculateEnergyPerCircuit ()
        {
            var ViewModel = new EnargyDataModel()
            {
                Sources=new VarianceReportMangment(_Context).GetAllSources(),
            };
            return View(ViewModel);
        }
        public IActionResult GetEnergyForCircuit(EnargyDataModel obj)
        {
            if(ModelState.IsValid)
            {
                obj.MID=5;
                var ViewModel = new EnargyReportMangement(_Context).CalCulateEnergyForCircuit(obj);
                if(ViewModel.EnargyValue!=0)
                {
                    return View(ViewModel);
                }
                else
                {
                    ModelState.AddModelError("", "There Is No Energy In this Circuit");
                    return View(ViewModel);
                }
            }
            else
            {
                obj.Sources=new VarianceReportMangment(_Context).GetAllSources();
                return View("CalCulateEnargy", obj);
            }
           
            
           
        }
    }
}

E2LabPower/Areas/Admin/Views/Enargy/CalCulateEnargy.cshtml
@model E2LabPower.Domain.Enargy.EnargyDataModel
@{
    ViewData["Title"]="CalCulateEnargy";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
}

<h2>CalCulate Energy</h2>
<script>
    $(function () {
        $("#SourceID").change(function () {

            var Url = '@Url.Action("GetLines", "Variance")';
            var DllSource = "#SourceID";
            $.getJSON(Url, { SourceID: $(DllSource).val() }, function (Data) {

                var items = "<option> select one Line </option> ";
                $("#LineID").empty();
                $.each(Data, function (i, row) {

                    items += "<option value='" + row.value + "'> " + row.text + " </option >"


                });
                $("#LineID").html(items);
            });

                });
            });

</script>
@using(Html.BeginForm("GetEnargy", "Enargy"))
{
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate)
                <input name="StartDate" class="form-control" id="StartDate" type="datetime-local" value="@DateTime.Now.Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate)
                <input name="EndDate" class="form-control" id="EndDate" type="datetime-local" value="@DateTime.Now.AddDays(1).Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.EndDate)
            </div>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SourceID)
        @Html.DropDownListFor(m => m.SourceID, new SelectList(Model.Sources, "SouceID", "SourceName"), "Select Circuit", new { @class = "form-control", id = "SourceID" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LineID)
        @Html.DropDownListFor(m => m.LineID, new SelectList(string.Empty, "LineID", "LineName"), "Select Line", new { @class = "form-control", id = "LineID" })
    </div>

    <button type="submit" class="btn btn-success">
        Get Energy
    </button>
}

<br />
<a href="~/Admin/Home/Index" style="margin-left:0px" class="btn btn-lg btn-primary">Admin Panel</a>

E2LabPower/Areas/Admin/Views/Enargy/CalculateEnergyPerCircuit.cshtml
@model E2LabPower.Domain.Enargy.EnargyDataModel
@{
    ViewData["Title"]="CalculateEnergyPerCircuit";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

<h2>Energy On Circuit</h2>
@using(Html.BeginForm("GetEnergyForCircuit", "Enargy"))
{
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate)
                <input name="StartDate" class="form-control" id="StartDate" type="datetime-local" value="@DateTime.Now.Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate)
                <input name="EndDate" class="form-control" id="EndDate" type="datetime-local" value="@DateTime.Now.AddDays(1).Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.EndDate)
            </div>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SourceID)
        @Html.DropDownListFor(m => m.SourceID, new SelectList(Model.Sources, "SouceID", "SourceName"), "Select Circuit", new { @class = "form-control", id = "SourceID" })
    </div>



    <button type="submit" class="btn btn-success">
        Get Energy
    </button>
}

<br />
<a href="~/Admin/Home/Index" style="margin-left:0px" class="btn btn-lg btn-primary">Admin Panel</a>

E2LabPower/Areas/Admin/Views/Enargy/GetEnargy.cshtml
@model E2LabPower.Domain.Enargy.EnargyDataModel
@{
    ViewData["Title"]="GetEnargy";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

<h2>Energy Report</h2>
<br />

<div class="text-danger" asp-validation-summary="ModelOnly"></div>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-info">Circuit Name</button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-info">Line Name</button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-info">Energy</button>
    </div>
</div>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@Model.SourceName</button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@Model.LineName</button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-danger">[@Model.EnargyValue KA/@Model.NumOfHours]<br /> [@Model.EnargyValueKW KW] </button>
    </div>
</div>
<br />
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4">
        <div id="container" style="min-width: 310px; max-width: 400px; height: 300px; margin: 0 auto"></div>

    </div>
    <div class="col-lg-4">
        <div id="container2" style="min-width: 310px; max-width: 400px; height: 300px; margin: 0 auto"></div>

    </div>
</div>

<br />


<div class="btn-group btn-group-justified" role="group" aria-label="..." >
    <div class="btn-group" role="group">
        
     
        @Html.ActionLink("Admin Panel", "Index", "Home", null, new { @class = "btn btn-success" })
    </div>
  
    <div class="btn-group" role="group">
        @Html.ActionLink("Energy", "CalCulateEnargy", "Enargy", null, new { @class = "btn btn-success" })
    </div>
</div>

<script>
Highcharts.chart('container', {

    chart: {
        type: 'gauge',
        plotBackgroundColor: null,
        plotBackgroundImage: null,
        plotBorderWidth: 0,
        plotShadow: false
    },

    title: {
        text: 'Energy'
    },

    pane: {
        startAngle: -150,
        endAngle: 150,
        background: [{
            backgroundColor: {
                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                stops: [
                    [0, '#FFF'],
                    [1, '#333']
                ]
            },
            borderWidth: 0,
            outerRadius: '109%'
        }, {
            backgroundColor: {
                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                stops: [
                    [0, '#333'],
                    [1, '#FFF']
                ]
            },
            borderWidth: 1,
            outerRadius: '107%'
        }, {
            // default background
        }, {
            backgroundColor: '#DDD',
            borderWidth: 0,
            outerRadius: '105%',
            innerRadius: '103%'
        }]
    },

    // the value axis
    yAxis: {
        min: 0,
        max: 100,

        minorTickInterval: 'auto',
        minorTickWidth: 1,
        minorTickLength: 10,
        minorTickPosition: 'inside',
        minorTickColor: '#666',

        tickPixelInterval: 30,
        tickWidth: 2,
        tickPosition: 'inside',
        tickLength: 10,
        tickColor: '#666',
        labels: {
            step: 2,
            rotation: 'auto'
        },
        title: {
            text: 'kA/ @Model.NumOfHours'
        },
        plotBands: [{
            from: 0,
            to: 120,
            color: '#55BF3B' // green
        }, {
            from: 120,
            to: 160,
            color: '#DDDF0D' // yellow
        }, {
            from: 160,
            to: 200,
            color: '#DF5353' // red
        }]
    },

    series: [{
        name: 'Enargy',
        data: [@Model.EnargyValue],
        tooltip: {
            valueSuffix: ' KA/@Model.NumOfHours'
        }
    }]

},
// Add some life
);</script>
<script>
Highcharts.chart('container2', {

    chart: {
        type: 'gauge',
        plotBackgroundColor: null,
        plotBackgroundImage: null,
        plotBorderWidth: 0,
        plotShadow: false
    },

    title: {
        text: 'Energy'
    },

    pane: {
        startAngle: -150,
        endAngle: 150,
        background: [{
            backgroundColor: {
                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                stops: [
                    [0, '#FFF'],
                    [1, '#333']
                ]
            },
            borderWidth: 0,
            outerRadius: '109%'
        }, {
            backgroundColor: {
                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                stops: [
                    [0, '#333'],
                    [1, '#FFF']
                ]
            },
            borderWidth: 1,
            outerRadius: '107%'
        }, {
            // default background
        }, {
            backgroundColor: '#DDD',
            borderWidth: 0,
            outerRadius: '105%',
            innerRadius: '103%'
        }]
    },

    // the value axis
    yAxis: {
        min: 0,
        max: 100,

        minorTickInterval: 'auto',
        minorTickWidth: 1,
        minorTickLength: 10,
        minorTickPosition: 'inside',
        minorTickColor: '#666',

        tickPixelInterval: 30,
        tickWidth: 2,
        tickPosition: 'inside',
        tickLength: 10,
        tickColor: '#666',
        labels: {
            step: 2,
            rotation: 'auto'
        },
        title: {
            text: 'KW'
        },
        plotBands: [{
            from: 0,
            to: 120,
            color: '#55BF3B' // green
        }, {
            from: 120,
            to: 160,
            color: '#DDDF0D' // yellow
        }, {
            from: 160,
            to: 200,
            color: '#DF5353' // red
        }]
    },

    series: [{
        name: 'Enargy',
        data: [@Model.EnargyValueKW],
        tooltip: {
            valueSuffix: ' KW'
        }
    }]

},
// Add some life
);</script>

E2LabPower/Areas/Admin/Views/Enargy/GetEnergyForCircuit.cshtml
@model E2LabPower.Domain.Enargy.EnargyDataModel
@{
    ViewData["Title"]="GetEnergyForCircuit";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}


<h2>Energy Report on @Model.SourceName</h2>
<br />

<div class="text-danger" asp-validation-summary="ModelOnly"></div>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-info">Circuit Name</button>
    </div>

    <div class="btn-group" role="group">
        <button type="button" class="btn btn-info">Energy</button>
    </div>
</div>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@Model.SourceName</button>
    </div>

    <div class="btn-group" role="group">
        <button type="button" class="btn btn-danger"> [@Model.EnargyValue KW] </button>
    </div>
</div>
<br />


    
        <div id="container" style="min-width: 310px; max-width: 400px; height: 300px; margin: 0 auto"></div>

<br />

<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">


        @Html.ActionLink("Admin Panel", "Index", "Home", null, new { @class = "btn btn-success" })
    </div>

    <div class="btn-group" role="group">
        @Html.ActionLink("Energy", "CalCulateEnargy", "Enargy", null, new { @class = "btn btn-success" })
    </div>
</div>
<script>
Highcharts.chart('container', {

    chart: {
        type: 'gauge',
        plotBackgroundColor: null,
        plotBackgroundImage: null,
        plotBorderWidth: 0,
        plotShadow: false
    },

    title: {
        text: 'Energy'
    },

    pane: {
        startAngle: -150,
        endAngle: 150,
        background: [{
            backgroundColor: {
                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                stops: [
                    [0, '#FFF'],
                    [1, '#333']
                ]
            },
            borderWidth: 0,
            outerRadius: '109%'
        }, {
            backgroundColor: {
                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                stops: [
                    [0, '#333'],
                    [1, '#FFF']
                ]
            },
            borderWidth: 1,
            outerRadius: '107%'
        }, {
            // default background
        }, {
            backgroundColor: '#DDD',
            borderWidth: 0,
            outerRadius: '105%',
            innerRadius: '103%'
        }]
    },

    // the value axis
    yAxis: {
        min: 0,
        max: 100,

        minorTickInterval: 'auto',
        minorTickWidth: 1,
        minorTickLength: 10,
        minorTickPosition: 'inside',
        minorTickColor: '#666',

        tickPixelInterval: 30,
        tickWidth: 2,
        tickPosition: 'inside',
        tickLength: 10,
        tickColor: '#666',
        labels: {
            step: 2,
            rotation: 'auto'
        },
        title: {
            text: 'kA/ @Model.NumOfHours'
        },
        plotBands: [{
            from: 0,
            to: 120,
            color: '#55BF3B' // green
        }, {
            from: 120,
            to: 160,
            color: '#DDDF0D' // yellow
        }, {
            from: 160,
            to: 200,
            color: '#DF5353' // red
        }]
    },

    series: [{
        name: 'Enargy',
        data: [@Model.EnargyValue],
        tooltip: {
            valueSuffix: ' KA/@Model.NumOfHours'
        }
    }]

},
// Add some life
);</script>