E2LabPower/Areas/Admin/Controllers/VarianceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using E2LabPower.Domain.Variance_Report;
using E2LabPower.Mangment.ReportsMangments;
using E2LabPower.Data;
using Microsoft.AspNetCore.NodeServices;
using E2LabPower.Domain;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using E2LabPower.Domain.Model;
using Microsoft.AspNetCore.Mvc.Rendering;
using E2LabPower.Mangment;
using E2LabPower.Domain.Var_ReportOverCircuit;

namespace E2LabPower.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VarianceController : Controller
    {
        private readonly DataContext _Context;
        private IMemoryCache memoryCache;
        private IConfiguration configuration;
        VarianceReportDataModel FinalObj = new VarianceReportDataModel();
        public VarianceController(DataContext context)
        {
            _Context=context;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult CalVar()
        {

            VarianceReportDataModel viewmodel = new VarianceReportDataModel()
            {
                SrouceList=new VarianceReportMangment(_Context).GetAllSources(),
            };

            return View(viewmodel);
        }
        [HttpGet]
        public JsonResult GetLines(int SourceID)
        {

            var Data = new LineService(_Context, memoryCache, configuration).GetLinesBySourceID(SourceID).ToList();
            return Json(new SelectList(Data, "LineID", "LineName"));
        }
        [HttpGet]
        public JsonResult GetLineMeasurments(int LineID)
        {

            var Data = new VarianceReportMangment(_Context).GetMeasurmentList(LineID);
            return Json(new SelectList(Data, "Id", "Name"));
        }
        [HttpPost]
        public IActionResult CalVariance(VarianceReportDataModel obj)
        {
            if(ModelState.IsValid)
            {
                var x = new VarianceReportMangment(_Context).CalculateVar(obj);
                if(x==null)
                {
                    return NotFound();
                }
                else if(x.Logs.Count()==0)
                {
                    return View("VarErr", x);
                }

                return View(x);
            }
            else
            {
                obj.SrouceList=new VarianceReportMangment(_Context).GetAllSources();
                return View("CalVar", obj);
            }
        }
        [HttpGet]
        public IActionResult VarCircuit()
        {
            VarReportOverCircuitModel viewModel = new VarReportOverCircuitModel()
            {
                Sources=new VarianceReportMangment(_Context).GetAllSources(),
            };
            return View(viewModel);
        }
        [HttpGet]
        public JsonResult GetMeasurments()
        {

            var Data = new VarianceReportMangment(_Context).GetAllMeasuremnt();
            return Json(new SelectList(Data, "Id", "Name"));
        }
        [HttpPost]
        public IActionResult CalVarOverCir(VarReportOverCircuitModel obj)
        {
            if(ModelState.IsValid)
            {
                var x = new VarianceReportMangment(_Context).CalculateVarOverCircuit(obj);

                return View(x);
            }
            else
            {
                obj.Sources=new VarianceReportMangment(_Context).GetAllSources();
                return View("VarCircuit", obj);
            }
        }
    }
}

E2LabPower/Areas/Admin/Views/Variance/CalVar.cshtml
@model E2LabPower.Domain.Variance_Report.VarianceReportDataModel

@{
    ViewData["Title"]="CalVar";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
}
<script>
    $(function () {
        $("#SourceID").change(function () {

            var Url = '@Url.Action("GetLines", "Variance")';
            var DllSource = "#SourceID";
            $.getJSON(Url, { SourceID: $(DllSource).val() }, function (Data) {

                var items = "<option> select one Line </option> ";
                $("#LineID").empty();
                $.each(Data, function (i, row) {

                    items += "<option value='" + row.value + "'> " + row.text + " </option >"


                });
                $("#LineID").html(items);
            });

                });
            });

</script>

<script>
    $(function () {
        $("#LineID").change(function () {

            var Url = '@Url.Action("GetLineMeasurments", "Variance")';
            var DllSource = "#LineID";
            $.getJSON(Url, { LineID: $(DllSource).val() }, function (Data) {

                var items = "<option> select one Measurment </option> ";
                $("#MID").empty();
                $.each(Data, function (i, row) {
                    
                    items += "<option value='" + row.value + "'> " + row.text + " </option >"


                });
                $("#MID").html(items);
            });

                });
            });

</script>
<h2>Variance Report</h2>

@using(Html.BeginForm("CalVariance", "Variance"))
{
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate)
                <input name="StartDate" class="form-control" id="StartDate" type="datetime-local" value="@DateTime.Now.Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate)
                <input name="EndDate" class="form-control" id="EndDate" type="datetime-local" value="@DateTime.Now.AddDays(1).Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.EndDate)
            </div>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SourceID)
        @Html.DropDownListFor(m => m.SourceID, new SelectList(Model.SrouceList, "SouceID", "SourceName"), "Select Circuit", new { @class = "form-control", id = "SourceID" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LineID)
        @Html.DropDownListFor(m => m.LineID, new SelectList(string.Empty, "LineID", "LineName"), "Select Line", new { @class = "form-control", id = "LineID" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.MID)
        @Html.DropDownListFor(m => m.MID, new SelectList(string.Empty, "Id", "Name"), "Select Measurment", new { @class = "form-control", id = "MID" })
    </div>
    <br />
    <button type="submit" class="btn btn-s btn-danger pull-right">
        Calculate Variance
    </button>
}

E2LabPower/Areas/Admin/Views/Variance/CalVarOverCir.cshtml
@model E2LabPower.Domain.Var_ReportOverCircuit.VarReportOverCircuitModel
@{
    ViewData["Title"] = "CalVarOverCir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.MName Variance over @Model.SourceName </h2>

@if(Model!=null)
{
    <div class="row">
        @foreach(var line in Model.Lines)
        {
            <div class="col-md-4">
                <h4 class="font-weight-bold">
                    <mark> Line :  @line.LineName </mark>
                </h4>





                @await Component.InvokeAsync("VarOverCir", new { chartData = line })

            </div>




        }
    </div>

    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-default">Variance Over @Model.SourceName</button>

        </div>
    </div>

    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-default">@Model.VarianceResults</button>

        </div>
    </div>

}
    

E2LabPower/Areas/Admin/Views/Variance/CalVariance.cshtml
@model E2LabPower.Domain.Variance_Report.VarianceReportDataModel
@{
    ViewData["Title"] = "CalVariance";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Variance Report on <b style="color:grey"> @Model.LineName</b> Applied on <b style="color:grey"> @Model.MeasureName</b>  </h2>


<div class="row">
    <div class="col-mid-12">

        <div id="x"></div>
    </div>
    <script class="form-inline">


        //highcharts code add here
        $(document).ready(function ()
        {

            Highcharts.chart('x',


           {
             chart: {type: 'line'},
             title: {text: '@Model.LineName'},
             data: {
                        rows:
                        [
                            [null, 'Values'], // series names
                            @foreach (var entry in Model.Logs)
                            {
                                <text>['@entry.Time.ToString("dd/MMM/yyyy [ HH:mm ]")', @entry.value],</text>
                            }
                        ]
                   }
           });
        });
    </script>
</div>
<br />

<div class="btn-group btn-group-justified" role="group" aria-label="...">
<div class="btn-group" role="group">
    <button type="button" class="btn btn-info">Maximum Value</button>
</div>
<div class="btn-group" role="group">
    <button type="button" class="btn btn-info">Minimum Value</button>
</div>
<div class="btn-group" role="group">
    <button type="button" class="btn btn-info">Variance</button>
</div>
</div>

<div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default">@Model.MaxValue</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default">@Model.MinValue</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-danger">@Model.Avg</button>
  </div>
</div>

E2LabPower/Areas/Admin/Views/Variance/VarCircuit.cshtml
@model E2LabPower.Domain.Var_ReportOverCircuit.VarReportOverCircuitModel
@{
    ViewData["Title"]="VarCircuit";
    Layout="~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
}

<h2>Get Variance Over a Circuit</h2>

<script>
    $(function () {
        $("#SourceID").change(function () {

            var Url = '@Url.Action("GetMeasurments", "Variance")';
            var DllSource = "#LineID";
            $.getJSON(Url, { LineID: $(DllSource).val() }, function (Data) {

                var items = "  ";
                $("#MID").empty();
                $.each(Data, function (i, row) {

                    items += "<option value='" + row.value + "'> " + row.text + " </option >"


                });
                $("#MID").html(items);
            });

                });
            });

</script>

@using(Html.BeginForm("CalVarOverCir", "Variance"))
{
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate)
                <input name="StartDate" class="form-control" id="StartDate" type="datetime-local" value="@DateTime.Now.Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>

        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate)
                <input name="EndDate" class="form-control" id="EndDate" type="datetime-local" value="@DateTime.Now.AddDays(1).Date.ToString("s")" data-val-required="field is required." data-val="true">
                @Html.ValidationMessageFor(m => m.EndDate)
            </div>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SourceID)
        @Html.DropDownListFor(m => m.SourceID, new SelectList(Model.Sources, "SouceID", "SourceName"), "Select Circuit", new { @class = "form-control", id = "SourceID" })
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.MID)
        @Html.DropDownListFor(m => m.MID, new SelectList(string.Empty, "Id", "Name"), "Select Measurment", new { @class = "form-control", id = "MID" })
    </div>
    <br />
    <button type="submit" class="btn btn-s btn-danger pull-right">
        Calculate Variance 
    </button>

}

E2LabPower/Areas/Admin/Views/Variance/VarErr.cshtml
@model E2LabPower.Domain.Variance_Report.VarianceReportDataModel
@{
    ViewData["Title"] = "VarErr";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 >Error</h2>

<b>  </b>
<div class="alert alert-danger" role="alert">
    This Line : @Model.LineName Has No Logs In this Measurment : @Model.MeasureName
</div>

<a href="~/Admin/Home/Index" style="margin-left:0px" class="btn btn-lg btn-primary">Admin Panel</a>