E2LabPower/Areas/Admin/Controllers/DataPerDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using E2LabPower.Data;
using E2LabPower.Mangment;

namespace E2LabPower.Areas.Admin.Controllers
{
    [Area("admin")]
    public class DataPerDayController : Controller
    {
        private DataContext _context;

        public DataPerDayController(DataContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult GetDataPerDay()
        {
            return View();
        }
        [HttpPost]
        public IActionResult DetaildDataperDay(DateTime startDate, DateTime EndDate)
        {
            if (ModelState.IsValid)
            {
                  var data = new SummryMangments(_context).GetsumperDay(startDate, EndDate);
                ViewData["sd"] = startDate;
                ViewData["ed"] = EndDate;
                return View(data);
            }
            else
            {
                return View("GetDataPerDay");
            }
        }

    }
}

E2LabPower/Areas/Admin/Views/DataPerDay/DetaildDataperDay.cshtml
@model IEnumerable<E2LabPower.Domain.DataPerDay.DataPerDayDataModel>
@{
    ViewData["Title"] = "DetaildDataperDay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Data Per Day</h2>

<div class="btn-group btn-group-justified" role="group" aria-label="...">
<div class="btn-group" role="group">

    <button type="button" class="btn btn-info">StartDate</button>
</div>

<div class="btn-group" role="group">
    <button type="button" class="btn btn-info">EndDate</button>
</div>
</div>
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@ViewData["sd"]</button>
    </div>

    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default">@ViewData["ed"] </button>
    </div>
</div>
<br />

<table class=" table table-bordered">
    <thead>
        <tr class="success">

            <th>
                @Html.DisplayNameFor(model => model.CirName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LineName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Voltage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ampere)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PowerFactor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Frequancy)
            </th>
            


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td class="danger">
                    @Html.DisplayFor(modelItem => item.CirName)
                </td>
                <td class="danger">
                    @Html.DisplayFor(modelItem => item.LineName)
                </td>
                <td class="warning">
                    @Html.DisplayFor(modelItem => item.Voltage)
                </td>
                <td class="warning">
                    @Html.DisplayFor(modelItem => item.Ampere)
                </td>
                <td class="warning">
                    @Html.DisplayFor(modelItem => item.PowerFactor)
                </td>
                <td class="warning">
                    @Html.DisplayFor(modelItem => item.Frequancy)
                </td>



            </tr>
        }
    </tbody>
</table>

E2LabPower/Areas/Admin/Views/DataPerDay/GetDataPerDay.cshtml
@model E2LabPower.Domain.DataPerDay.DataPerDayDataModel
@{
    ViewData["Title"] = "GetDataPerDay";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
}

<h2>Average Data Per Day Report</h2>


@using (Html.BeginForm("DetaildDataperDay", "DataPerDay"))
{<div class="text-danger" asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        @Html.LabelFor(m => m.startDate)
        <input name="startDate" class="form-control" id="startDate" type="date" data-val-required="Start Date is Required." data-val="true">
        @Html.ValidationMessageFor(m => m.startDate)
    </div>
        <div class="form-group">
            @Html.LabelFor(m => m.EndDate)
            <input name="EndDate" class="form-control" id="EndDate" type="date" data-val-required="End Date is Requied" data-val="true">
            @Html.ValidationMessageFor(m => m.EndDate)
        </div>


        <button type="submit" class="btn btn-s btn-danger pull-right">
            Calculate
        </button>
}